print("----------------------------------------------------------")
print("Daftar Tarif untuk Setiap Kenaikan 50 Km")
print("----------------------------------------------------------")
x = int(input("Masukkan masukan jarak yang sudah ditempuh x50 km: "))
print("----------------------------------------------------------")
print("Baik kendaraan sudah menempuh", x * 50, "km")
print("----------------------------------------------------------")
print("Tarif H-6")
print(" - Kendaraan pribadi : ", 1000 * (x * 50))
print(" - Bus               : ", 1500 * (x * 50)) 
print(" - Truk              : ", 2000 * (x * 50))

print("Tarif H-1")
print(" - Kendaraan pribadi : ", int((1000 * (x * 50)) - (0.2 * (1000 * (x * 50)))))
print(" - Bus               : ", int((1500 * (x * 50)) - (0.2 * (1500 * (x * 50))))) 
print(" - Truk              : ", int((2000 * (x * 50)) - (0.2 * (2000 * (x * 50)))))
print("----------------------------------------------------------")
